export enum ChartDataItemsActionTypes {
    CHART_DATA_SHOW_STATE_CHANGE = 'CHART_DATA_SHOW_STATE_CHANGE',
    CHART_DATA_ADDED = 'CHART_DATA_ADDED',
    CHART_DATA_REMOVED = 'CHART_DATA_REMOVED',
    CHART_DATA_INFO_SHOWN = 'CHART_DATA_INFO_SHOWN',
    CHART_DATA_INFO_HIDDEN = 'CHART_DATA_INFO_HIDDEN',
    CHART_DATA_COLOR_CHANGED = 'CHART_DATA_COLOR_CHANGED'
}